Sprint56
dnsoftware/gophermart2 pull request #1
Opened 2024-03-26 08:57 UTC by dnsoftware

2024-03-27 21:08 UTC, Bazys commented on internal/gophermart/handlers/routes.go
> +	userID := uid.(int64)
вытащили из контекста, а вдруг там совсем не то что ожидаем? надо бы проверять

2024-03-27 21:19 UTC, Bazys requested changes
по коду вопрос почти нет, 429 ошибку обрабатываешь, за горутинами следишь, всё супер!
Теперь давай увеличим покрытие тестами. 0.3% это совсем смех

2024-03-27 21:19 UTC, Bazys commented on internal/gophermart/handlers/routes.go
> +	userID := uid.(int64)
вытащили из контекста, а вдруг там совсем не то что ожидаем? надо бы проверять

2024-03-27 21:19 UTC, Bazys commented on internal/constants/constants.go
> +	DBContextTimeout  time.Duration = time.Duration(50) * time.Second // длительность запроса в контексте работы с БД и сетью
почему именно 50 а не 60 например?

2024-03-27 21:19 UTC, Bazys commented on internal/constants/statuses.go
> +		return 200, "успешная обработка запроса"
начал с константами работать, то может и повторяющиеся строки засунешь в константы

2024-03-31 19:40 UTC, dnsoftware commented on internal/constants/constants.go
> +	DBContextTimeout  time.Duration = time.Duration(50) * time.Second // длительность запроса в контексте работы с БД и сетью
Изначально там было 10 секунд.
Потом вылезла ошибка "Context Deadline Exceeded" и в процессе поиска поставил там 50, чтоб наверняка)).
А вернуть назад забыл.

Верну 10, этого должно быть более чем достаточно

2024-04-03 08:38 UTC, Bazys approved these changes
25.7% это конечно не 40, сейчас достаточно, а вот дальше в процессе учебы и развития проекта, надо будет поднимать.
Так же сразу ко всем проектам приучайся подключать `goimports` или даже `gofumpt`.
И очень часто ты не используешь переменные которые есть в сигнатуре функции, если они не нужны, но сигнатуру изменить не можешь используй _

2024-04-03 13:40 UTC, merged